<?php

// CREATE (POCKET) TAG TO (SLACK) CHANNEL MAP
$map = array();

$map['POCKET_TAG_NAME']='DESTINATION_SLACK_CHANNEL_NAME';

$map['OTHER POCKET_TAG_NAME']='OTHER_DESTINATION_SLACK_CHANNEL_NAME';

?>
